import 'package:flutter/material.dart';

import 'package:moments/utilis/design.dart';

class PassportShootPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor:
            Colors.transparent, // Set the background color to transparent
        elevation: 0,
        title: Text('Passport Photo Shoot'),
      ),
      body: SingleChildScrollView(
        child: Container(
          padding: EdgeInsets.all(8.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // MyLayout(
              //   title: 'The Most Popular',
              //   imagePaths: [
              //     'asset/imges/passport/passport.jpg',
              //     'asset/imges/passport/visa.jpg',
              //     'asset/imges/adhar.jpg',
              //   ],
              //   descriptions: ['Passport', 'visa', 'Addhar card'],
              //   size: ['2x2', '3x3', '2x2', '4x4'],
              // ),
              MyLayout(title: 'Offical document in india', imagePaths: [
                'asset/imges/passport/passport.jpg',
                'asset/imges/driving.jpg',
                'asset/imges/pancard.png',
                'asset/imges/adhar.jpg',
              ], descriptions: [
                'Indian Passport',
                'Driving License',
                'PAN card',
                'Addhar card'
              ], size: [
                '2x2 in',
                '35x45 mm',
                '25x35 mm',
                '35x45 mm'
              ]),
              MyLayout(title: 'Other Documents', imagePaths: [
                'asset/imges/passport/eu.jpg',
                'asset/imges/passport/link.jpg',
                'asset/imges/passport/cv.jpg',
              ], descriptions: [
                'EU Blue Card',
                'Linkedin Photo',
                'Photo for your CV'
              ], size: [
                '3.5x4.5',
                '400x400 px',
                '3.5x4.5 cm'
              ]),
              MyLayoutForVisa(title: 'Visas', imagePaths: [
                'asset/flag/afgha.jpg',
                'asset/flag/alba.jpg',
                'asset/flag/alge.jpg',
                'asset/flag/argen.jpg',
                'asset/flag/armenia.jpg',
                'asset/flag/barhin.jpg',
                'asset/flag/bangla.jpg',
                'asset/flag/belarus.jpg',
                'asset/flag/belgium.jpg',
                'asset/flag/bolivia.jpg',
                'asset/flag/brazil.jpg',
                'asset/flag/uk.jpg',
                'asset/flag/bur.jpg',
                'asset/flag/cambo.jpg',
                'asset/flag/came.jpg',
                'asset/flag/chile.jpg',
                'asset/flag/denmark.jpg',
                'asset/flag/egypt.jpg',
                'asset/flag/estonia.jpg',
                'asset/flag/germany.jpg',
                'asset/flag/ghana.jpg',
                'asset/flag/greece.jpg',
                'asset/flag/hungray.jpg',
                'asset/flag/hongkong.jpg',
                'asset/flag/india.jpg',
                'asset/flag/indonesia.jpg',
                'asset/flag/iran.jpg',
                'asset/flag/iraq.jpg',
                'asset/flag/ireland.jpg',
                'asset/flag/israil.jpg',
                'asset/flag/italey.jpg',
                'asset/flag/israil.jpg',
                'asset/flag/japan.jpg',
                'asset/flag/jamaica.jpg',
                'asset/flag/laos.jpg',
                'asset/flag/lebanon.jpg',
                'asset/flag/leshoto.jpg',
                'asset/flag/libya.jpg',
                'asset/flag/lux.jpg',
                'asset/flag/macau.jpg',
                'asset/flag/mad.jpg',
                'asset/flag/mm.jpg',
                'asset/flag/moroco.jpg',
                'asset/flag/mexico.jpg',
                'asset/flag/mongoli.jpg',
                'asset/flag/Mozambique.jpg',
                'asset/flag/nepal.jpg',
                'asset/flag/nethreland.jpg',
                'asset/flag/new zealand.jpg',
                'asset/flag/niger.jpg',
                'asset/flag/nigeria.jpg',
                'asset/flag/norway.jpg',
                'asset/flag/man.jpg',
                'asset/flag/pakistan.jpg',
                'asset/flag/panama.jpg',
                'asset/flag/philipines.jpg',
                'asset/flag/poland.jpg',
                'asset/flag/qatar.jpg',
                'asset/flag/rusia.jpg',
                'asset/flag/rwand.jpg',
                'asset/flag/slova.jpg',
                'asset/flag/somalia.jpg',
                'asset/flag/sk.jpg',
                'asset/flag/spain.jpg',
                'asset/flag/sril.jpg',
                'asset/flag/sweden.jpg',
                'asset/flag/switerzerland.jpg',
                'asset/flag/taiwan.jpg',
                'asset/flag/thailand.jpg',
                'asset/flag/turkey.jpg',
                'asset/flag/uk.jpg',
                'asset/flag/ukrain.jpg',
                'asset/flag/usa.jpg',
                'asset/flag/zimbabwe.jpg',
              ], descriptions: [
                'Afghanistan',
                'Albania',
                'Algeria',
                'Argentina',
                'Armenia Visa',
                'Bahrin',
                'Bangladesh',
                'Belarus',
                'Belgium',
                'Bolivia',
                'Brazil',
                'Britain',
                'Burkina Faso',
                'Cambodia',
                'Cameroon Visa',
                'Chile',
                'Denmark',
                'Egypt',
                'Estonia',
                'Germany',
                'Ghana',
                'Guinea - Bissau',
                'Honduras',
                'Hong KOng',
                'India',
                'Indonesia',
                'Iran',
                'Iraq',
                'Irish',
                'Israel',
                'Italy',
                'Ivory Coast',
                'Japan',
                'Jordan',
                'Laos',
                'Lebanon',
                'Lesotho',
                'Libya',
                'Luxembourg',
                'Macau',
                'Madagascar',
                'Malaysia',
                'Mauritania',
                'Mexico',
                'Mongolia',
                'Mozambique',
                'Nepal',
                'Netherlands',
                'New Zealand',
                'Niger',
                'Nigeria',
                'Norway',
                'Oman',
                'Pakistan',
                'Palestinian Territories',
                'Philippines',
                'Poland',
                'Qatar',
                'Russia',
                'Rwanda',
                'Slovenia',
                'Somalia',
                'South Korea',
                'Spain',
                'Sri Lanka',
                'Swedan',
                'Switzerland',
                'Taiwan',
                'Thailand',
                'Turkish',
                'UAE',
                'Uganda',
                'Uzbekistan',
                'Zambia',
              ], size: [
                '2x2 in',
                '36x47 mm',
                '2x2 in',
                '35x45 mm',
                '35x45 mm',
                '51x51 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '2x2 in',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '45x45 mm',
                '35x45 mm',
                '35x45 mm',
                '40x60 mm',
                '40x50 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '30x40 mm',
                '51x51 mm',
                '40x50 mm',
                '51x51 mm',
                '51x51 mm',
                '35x45 mm',
                '51x51 mm',
                '35x45 mm',
                '55x55 mm',
                '35x45 mm',
                '2x2 mm',
                '45x45 mm',
                '50x50 mm',
                '50x50 mm',
                '35x45 mm',
                '51x51 mm',
                '40x60 mm',
                '35x45 mm',
                '33x48 mm',
                '35x45 mm',
                '35x50 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '2x2 in',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '500x500 px',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '35x45 mm',
                '51x51 mm',
                '35x45 mm',
              ])
            ],
          ),
        ),
      ),
    );
  }
}
